const express = require('express');
const cors = require('cors');
const fetch = require('node-fetch');

const app = express();
app.use(cors());
app.use(express.json());

const PORT = process.env.PORT || 3000;

// --- Data sources -----------------------------------------------------
// The old version scraped FixMyStreet's HTML report list with CSS selectors
// (.item-list__item / h3 a) that no longer match the site's markup, so it
// was silently returning zero reports. FixMyStreet publishes proper RSS
// feeds instead — including per-ward feeds with real georss:point
// coordinates, categories, and pubDates — which is what we use now.
//
// Penistone East + West are the two electoral wards that cover the
// Penistone area (and catch villages a simple keyword list would miss,
// e.g. Ingbirchworth, Silkstone, Thurgoland). The borough-wide feed is
// kept as a fallback, filtered to Penistone-area keywords, in case a
// relevant report ever sits just outside those ward boundaries.
const SOURCES = [
  { name: 'Penistone East ward', url: 'https://www.fixmystreet.com/rss/reports/Barnsley/Penistone+East?type=MTW', wardMatch: true },
  { name: 'Penistone West ward', url: 'https://www.fixmystreet.com/rss/reports/Barnsley/Penistone+West?type=MTW', wardMatch: true },
  { name: 'Barnsley borough (keyword filtered)', url: 'https://www.fixmystreet.com/rss/reports/Barnsley', wardMatch: false }
];

const VILLAGE_KEYWORDS = [
  'penistone', 'thurlstone', 'millhouse green', 'hoylandswaine', 'cubley',
  'oxspring', 'springvale', 'spring vale', 'ingbirchworth', 'hunshelf',
  'langsett', 'midhopestones', 'bullhouse', 'gunthwaite', 'silkstone'
];

let cachedReports = [];
let lastFetch = 0;
let sourceCache = {}; // source name -> last successful item list, so one flaky source doesn't blank the others

// --- Small XML/HTML helpers -------------------------------------------
// RSS description fields arrive XML-entity-encoded (so a literal "<br>"
// shows up as "&lt;br&gt;"). Decode first, THEN strip/parse the HTML
// that's embedded inside.
function decodeEntities(str) {
  return (str || '')
    .replace(/&lt;/g, '<')
    .replace(/&gt;/g, '>')
    .replace(/&quot;/g, '"')
    .replace(/&#39;/g, "'")
    .replace(/&#10;/g, '\n')
    .replace(/&amp;/g, '&');
}

function extractTag(itemXml, tag) {
  const re = new RegExp(`<${tag}[^>]*>([\\s\\S]*?)<\\/${tag}>`, 'i');
  const m = itemXml.match(re);
  return m ? m[1].trim() : '';
}

function cleanTitle(title) {
  // FixMyStreet titles end with ", 24th August" — drop that, we use pubDate instead.
  const t = title.replace(/,\s*\d{1,2}(st|nd|rd|th)\s+[A-Za-z]+$/, '').trim();
  return t || 'Untitled report';
}

function extractLoc(desc) {
  const m = desc.match(/Nearest road to the pin placed on the map \(automatically generated by OpenStreetMap\):\s*([^<\n]+)/i);
  return m ? m[1].trim() : 'Penistone area';
}

function extractPhoto(desc) {
  const m = desc.match(/<img[^>]+src="([^"]+)"/i);
  return m ? m[1] : null;
}

function cleanDescription(desc) {
  return desc
    .replace(/<img[^>]*>/gi, '')
    .replace(/Nearest road to the pin[\s\S]*$/i, '')
    .replace(/<br\s*\/?>/gi, ' ')
    .replace(/<a[^>]*>[\s\S]*?<\/a>/gi, '')
    .replace(/&#\d+;/g, ' ') // occasional double-encoded entities in reporter-submitted text
    .replace(/\s+/g, ' ')
    .trim();
}

function mapCategory(category, title) {
  const c = (category || '').toLowerCase();
  const t = (title || '').toLowerCase();
  if (c.includes('pothole') || c.includes('road') || c.includes('highway') || c.includes('pavement') || c.includes('footpath') || t.includes('pothole')) return 'pothole';
  if (c.includes('rubbish') || c.includes('flytip') || c.includes('flyposting') || c.includes('street cleaning') || c.includes('dog fouling') || t.includes('litter') || t.includes('rubbish') || t.includes('dump')) return 'litter';
  if (c.includes('street lighting') || t.includes('light') || t.includes('lamp')) return 'lighting';
  if (t.includes('noise') || t.includes('anti-social') || t.includes('anti social') || t.includes('asb')) return 'asb';
  return 'other';
}

// --- Fetching one RSS source --------------------------------------------
function sleep(ms) { return new Promise(resolve => setTimeout(resolve, ms)); }

async function fetchRssSourceOnce(source) {
  const res = await fetch(source.url, {
    headers: {
      // FixMyStreet's RSS endpoint appears to be flaky/rate-limited against
      // generic bot-style User-Agents — a realistic browser UA + Accept
      // headers noticeably cuts down on 503s.
      'User-Agent': 'Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/124.0.0.0 Safari/537.36',
      'Accept': 'application/rss+xml, application/xml;q=0.9, text/xml;q=0.8, */*;q=0.7',
      'Accept-Language': 'en-GB,en;q=0.9'
    },
    timeout: 15000
  });
  if (!res.ok) throw new Error(`HTTP ${res.status}`);
  const xml = await res.text();
  const itemBlocks = xml.match(/<item>[\s\S]*?<\/item>/g) || [];
  const items = [];

  itemBlocks.forEach(block => {
    const rawTitle = decodeEntities(extractTag(block, 'title'));
    const link = extractTag(block, 'link').trim();
    const rawDesc = decodeEntities(extractTag(block, 'description'));
    const category = extractTag(block, 'category');
    const pubDate = extractTag(block, 'pubDate');
    const pointText = extractTag(block, 'georss:point');

    let lat = null, lng = null;
    if (pointText) {
      const parts = pointText.split(/\s+/).map(Number);
      if (parts.length === 2 && !isNaN(parts[0]) && !isNaN(parts[1])) {
        [lat, lng] = parts;
      }
    }

    const title = cleanTitle(rawTitle);
    const combined = (title + ' ' + rawDesc).toLowerCase();

    // The borough-wide feed covers all of Barnsley, so only keep
    // Penistone-area items from it. The two ward feeds are already scoped.
    if (!source.wardMatch && !VILLAGE_KEYWORDS.some(v => combined.includes(v))) return;

    if (!link) return;

    items.push({
      id: link,
      title,
      loc: extractLoc(rawDesc),
      area: 'Penistone',
      lat,
      lng,
      type: mapCategory(category, title),
      severity: /pothole|flood|dangerous|blocked|collapsed|unsafe|sunk/i.test(title) ? 'high' : 'normal',
      ts: pubDate ? new Date(pubDate).getTime() : Date.now(),
      time: 'Recent',
      url: link,
      media: extractPhoto(rawDesc),
      desc: cleanDescription(rawDesc),
      source: source.name
    });
  });

  return items;
}

// Retry transient failures (503s, timeouts) a couple of times with backoff
// before giving up on a source for this cycle.
async function fetchRssSource(source, attempts = 3) {
  let lastErr;
  for (let i = 0; i < attempts; i++) {
    try {
      return await fetchRssSourceOnce(source);
    } catch (err) {
      lastErr = err;
      console.warn(`  ${source.name} attempt ${i + 1}/${attempts} failed: ${err.message}`);
      if (i < attempts - 1) await sleep(1500 * (i + 1)); // 1.5s, then 3s
    }
  }
  throw lastErr;
}

async function fetchReports() {
  console.log('Fetching reports from all sources...');
  const results = await Promise.allSettled(SOURCES.map(source => fetchRssSource(source)));

  const merged = new Map(); // de-dupe by report URL (a report can appear in both a ward feed and the fallback feed)
  results.forEach((r, i) => {
    const name = SOURCES[i].name;
    if (r.status === 'fulfilled') {
      sourceCache[name] = r.value;
      console.log(`  ${name}: ${r.value.length} reports`);
    } else {
      console.error(`  ${name} failed after retries: ${r.reason && r.reason.message} — using last known data (${(sourceCache[name] || []).length} reports)`);
    }
    (sourceCache[name] || []).forEach(item => merged.set(item.id, item));
  });

  cachedReports = Array.from(merged.values()).sort((a, b) => b.ts - a.ts);
  lastFetch = Date.now();
  console.log(`Loaded ${cachedReports.length} total reports`);
}

// Fetch on start + every 12 minutes
fetchReports();
setInterval(fetchReports, 12 * 60 * 1000);

app.get('/api/reports', (req, res) => {
  res.json({
    updated: new Date(lastFetch).toISOString(),
    count: cachedReports.length,
    reports: cachedReports
  });
});

app.get('/', (req, res) => {
  res.send('Penistone Insight Hub Backend is running');
});

app.listen(PORT, () => {
  console.log(`Server running on port ${PORT}`);
});
